amcl:
  # 粒子滤波核心参数
  min_particles: 100       # 最小粒子数（原默认30）1000
  max_particles: 2000       # 最大粒子数（原默认5000）5000
  kld_err: 0.05            # 采样误差阈值（已设置）
  kld_z: 0.99              # 正态分布分位数
  
  # 传感器模型参数  
  laser_min_range: 0.02     # 最小有效距离
  laser_max_range: 4    # 最大有效距离
  laser_max_beams: 60       # 使用激光束数量
  laser_model_type: "likelihood_field"  # 推荐使用似然场模型  
  # laser_model_type: "beam"   # 使用更简单的模型

  # 里程计噪声模型
  odom_model_type: "omni"
  odom_alpha1: 0.1         # 降低旋转噪声（原0.2）0.01
  odom_alpha2: 0.1         # 降低平移噪声（原0.2）
  odom_alpha3: 0.1        # 新增：旋转相关平移噪声
  odom_alpha4: 0.1         # 新增：平移相关旋转噪声
  
  # 更新阈值
  update_min_d: 0.02         # 降低移动距离阈值（原0.1）
  update_min_a: 0.02         # 降低旋转角度阈值（原0.2）
  resample_interval: 1       # 每次更新都重采样（默认2）
  transform_tolerance: 0.5 
  # 恢复行为
  # recovery_alpha_slow: 0.001
  # recovery_alpha_fast: 0.1