# # DWA局部规划器配置（适合麦轮底盘）
# DWAPlannerROS:

#   # 关键参数调整
#   max_vel_x: 0.5
#   min_vel_x: -0.5
#   max_vel_y: 0.5  # 麦轮专用
#   min_vel_y: -0.5
#   holonomic_robot: true  # 启用全向移动
  
#   # 容错参数
#   xy_goal_tolerance: 0.2  # 增大目标容差
#   yaw_goal_tolerance: 0.2
#   latch_xy_goal_tolerance: true


#   # 加速度限制
#   acc_lim_x: 1.0
#   acc_lim_y: 1.0
#   acc_lim_theta: 2.0
  
#   # 轨迹评分参数
#   xy_goal_tolerance: 0.10    # XY目标容忍度
#   yaw_goal_tolerance: 0.05   # 角度目标容忍度
#   latch_xy_goal_tolerance: true
  
#   # 麦轮底盘专用参数
#   holonomic_robot: true      # 全向移动机器人
#   heading_lookahead: 0.325
#   heading_scoring: false
#   heading_scoring_timestep: 0.8
  
#   # 控制器频率
#   sim_time: 1.7
#   sim_granularity: 0.025
#   vx_samples: 20
#   vy_samples: 20            # 增加Y方向采样（麦轮专用）
#   theta_samples: 40


DWAPlannerROS:
  # 速度限制（麦轮全向）
  max_vel_x: 0.5       # 前进最大速度(m/s)
  min_vel_x: -0.5      # 后退速度（比前进稍小）
  max_vel_y: 0.5       # 横向移动速度（保守值）
  min_vel_y: -0.5
  max_vel_theta: 0.05   # 旋转速度(rad/s)
  min_vel_theta: -0.05

  # 加速度限制（更安全的值）
  acc_lim_x: 1       # X轴加速度(m/s²)
  acc_lim_y: 1       # Y轴加速度  
  acc_lim_theta: 0.05    # 旋转加速度(rad/s²)

  # 目标容差（统一值）
  xy_goal_tolerance: 0.15    # XY容差(m)
  yaw_goal_tolerance: 0.15    # 角度容差(rad)
  latch_xy_goal_tolerance: true

  # 全向移动配置
  holonomic_robot: true
  heading_lookahead: 0.5     # 缩短前瞻距离
  heading_scoring: false
  heading_scoring_timestep: 0.5

  # 轨迹生成参数
  sim_time: 1.7              # 缩短预测时长（原1.7）
  sim_granularity: 0.05      # 降低轨迹分辨率（原0.025）
  vx_samples: 10            # 减少采样点（原20）
  vy_samples: 10
  theta_samples: 10

  # 避障关键参数
  path_distance_bias: 0.1    # 路径跟随权重
  goal_distance_bias: 0.9    # 目标点权重
  occdist_scale: 0.1         # 障碍物避让权重
  stop_time_buffer: 0.2      # 紧急停止缓冲时间