# DWA局部规划器配置（适合麦轮底盘）
DWAPlannerROS:
  # 速度限制（麦轮底盘支持全向移动）
  max_vel_x: 0.5
  min_vel_x: -0.2
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_rot_vel: 1.0
  min_rot_vel: 0.1
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  
  # 加速度限制
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 2.0
  
  # 轨迹评分参数
  xy_goal_tolerance: 0.10    # XY目标容忍度
  yaw_goal_tolerance: 0.05   # 角度目标容忍度
  latch_xy_goal_tolerance: true
  
  # 麦轮底盘专用参数
  holonomic_robot: true      # 全向移动机器人
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  
  # 控制器频率
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 20            # 增加Y方向采样（麦轮专用）
  theta_samples: 40
