global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  
  static_map: true
  rolling_window: false  # 禁用滚动窗口

  # 使用plugins配置替代
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  # # 静态层配置
  # static_layer:
  #   map_topic: /map
    
  # # 障碍层配置
  # obstacle_layer:
  #   observation_sources: scan
  #   scan:
  #     topic: /scan
  #     data_type: LaserScan
  #     clearing: true
  #     marking: true
  #     max_obstacle_height: 2.0
      
  # # 膨胀层配置
  # inflation_layer:
  #   inflation_radius: 0.33
  #   cost_scaling_factor: 5.0

static_layer:
  map_topic: /map
  unknown_cost_value: -1  # 标记未知区域
  trinary_costmap: true   # 简化地图表示
  
# 膨胀层配置
inflation_layer:
  inflation_radius: 0.40   # 可适当减小
  cost_scaling_factor: 3.0
  inflate_unknown: false  # 不膨胀未知区域