# # 全局代价地图配置
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 1.0
#   publish_frequency: 0.5
#   static_map: true
#   rolling_window: false


# global_costmap_params.yaml
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  
  # 移除这行（如果存在）
  # static_map: true
  
  # 使用plugins配置替代
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  # 静态层配置
  static_layer:
    map_topic: /map
    
  # 障碍层配置
  obstacle_layer:
    observation_sources: scan
    scan:
      topic: /scan
      data_type: LaserScan
      clearing: true
      marking: true
      max_obstacle_height: 2.0
      
  # 膨胀层配置
  inflation_layer:
    inflation_radius: 0.03
    cost_scaling_factor: 5.0